name: flutter_app_integrity
description: A Flutter plugin to detect rooted/jailbroken devices, emulators, debuggers, and app tampering on Android and iOS.
version: 0.0.1
homepage: https://github.com/yourusername/flutter_app_integrity
 
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"
 
flutter:
  plugin:
    platforms:
      android:
        package: com.anuj.flutter_app_integrity
        pluginClass: FlutterAppIntegrityPlugin
      ios:
        pluginClass: FlutterAppIntegrityPlugin
 
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

 
dev_dependencies:
  flutter_test:
    sdk: flutter
 